name: 'Poll Site version'
description: 'Polls a site until the version meta tag matches the specified version'
inputs:
  site-url:
    description: 'URL to poll'
    required: true
  desired-version:
    description: 'Stop polling when the site returns this version'
    required: true
  poll-interval:
    description: 'How often to poll the site (in seconds)'
    required: false
    default: '30'
  timeout:
    description: 'Timeout in seconds'
    required: false
    default: '600'
runs:
  using: 'node12'
  main: 'dist/index.js'

